openapi: 3.0.4
info:
  contact:
    email: support@fenix-alliance.com
    name: Fenix Alliance Inc.
    url: https://fenixalliance.com.co/Support
  license:
    name: Fenix Alliance Inc.
    url: https://fenix-alliance.com.co/Legal/Policies/eula
  termsOfService: https://absuite.net/eula
  title: TimeTrackerService
  version: 2.0.0.0
servers:
- description: Alliance Business Suite API
  url: "{server}"
  variables:
    server:
      default: https://absuite.net
      description: ABS instance base URL
      enum:
      - https://absuite.net
      - https://test.absuite.net
      - https://dev.absuite.net
      - https://localhost:44388
tags:
- name: FenixAlliance.ABS.Web
- name: ProjectTimeLogs
- name: TimeLogApprovals
paths:
  /version:
    get:
      responses:
        "200":
          description: OK
      tags:
      - FenixAlliance.ABS.Web
      x-accepts:
      - application/json
  /health:
    get:
      responses:
        "200":
          description: OK
      tags:
      - FenixAlliance.ABS.Web
      x-accepts:
      - application/json
  /hello:
    get:
      responses:
        "200":
          description: OK
      tags:
      - FenixAlliance.ABS.Web
      x-accepts:
      - application/json
  /register:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
        required: true
      responses:
        "200":
          description: OK
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
          description: Bad Request
      tags:
      - FenixAlliance.ABS.Web
      x-content-type: application/json
      x-accepts:
      - application/problem+json
  /login:
    post:
      parameters:
      - explode: true
        in: query
        name: useCookies
        required: false
        schema:
          type: boolean
        style: form
      - explode: true
        in: query
        name: useSessionCookies
        required: false
        schema:
          type: boolean
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessTokenResponse'
          description: OK
      tags:
      - FenixAlliance.ABS.Web
      x-content-type: application/json
      x-accepts:
      - application/json
  /refresh:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessTokenResponse'
          description: OK
      tags:
      - FenixAlliance.ABS.Web
      x-content-type: application/json
      x-accepts:
      - application/json
  /confirmEmail:
    get:
      operationId: MapIdentityApi-/confirmEmail
      parameters:
      - explode: true
        in: query
        name: userId
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: code
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: changedEmail
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          description: OK
      tags:
      - FenixAlliance.ABS.Web
      x-accepts:
      - application/json
  /resendConfirmationEmail:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResendConfirmationEmailRequest'
        required: true
      responses:
        "200":
          description: OK
      tags:
      - FenixAlliance.ABS.Web
      x-content-type: application/json
      x-accepts:
      - application/json
  /forgotPassword:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ForgotPasswordRequest'
        required: true
      responses:
        "200":
          description: OK
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
          description: Bad Request
      tags:
      - FenixAlliance.ABS.Web
      x-content-type: application/json
      x-accepts:
      - application/problem+json
  /resetPassword:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPasswordRequest'
        required: true
      responses:
        "200":
          description: OK
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
          description: Bad Request
      tags:
      - FenixAlliance.ABS.Web
      x-content-type: application/json
      x-accepts:
      - application/problem+json
  /manage/2fa:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TwoFactorRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TwoFactorResponse'
          description: OK
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
          description: Bad Request
        "404":
          description: Not Found
      tags:
      - FenixAlliance.ABS.Web
      x-content-type: application/json
      x-accepts:
      - application/json
      - application/problem+json
  /manage/info:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InfoResponse'
          description: OK
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
          description: Bad Request
        "404":
          description: Not Found
      tags:
      - FenixAlliance.ABS.Web
      x-accepts:
      - application/json
      - application/problem+json
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InfoRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InfoResponse'
          description: OK
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
          description: Bad Request
        "404":
          description: Not Found
      tags:
      - FenixAlliance.ABS.Web
      x-content-type: application/json
      x-accepts:
      - application/json
      - application/problem+json
  /Account/PerformExternalLogin:
    post:
      requestBody:
        content:
          multipart/form-data:
            encoding:
              provider:
                style: form
              returnUrl:
                style: form
            schema:
              $ref: '#/components/schemas/_Account_PerformExternalLogin_post_request'
          application/x-www-form-urlencoded:
            encoding:
              provider:
                style: form
              returnUrl:
                style: form
            schema:
              $ref: '#/components/schemas/_Account_PerformExternalLogin_post_request'
      responses:
        "200":
          description: OK
      tags:
      - FenixAlliance.ABS.Web
      x-content-type: multipart/form-data
      x-accepts:
      - application/json
  /Account/Logout:
    post:
      requestBody:
        content:
          multipart/form-data:
            encoding:
              returnUrl:
                style: form
            schema:
              $ref: '#/components/schemas/_Account_Logout_post_request'
          application/x-www-form-urlencoded:
            encoding:
              returnUrl:
                style: form
            schema:
              $ref: '#/components/schemas/_Account_Logout_post_request'
      responses:
        "200":
          description: OK
      tags:
      - FenixAlliance.ABS.Web
      x-content-type: multipart/form-data
      x-accepts:
      - application/json
  /Account/Manage/LinkExternalLogin:
    post:
      requestBody:
        content:
          multipart/form-data:
            encoding:
              provider:
                style: form
            schema:
              $ref: '#/components/schemas/_Account_Manage_LinkExternalLogin_post_request'
          application/x-www-form-urlencoded:
            encoding:
              provider:
                style: form
            schema:
              $ref: '#/components/schemas/_Account_Manage_LinkExternalLogin_post_request'
      responses:
        "200":
          description: OK
      tags:
      - FenixAlliance.ABS.Web
      x-content-type: multipart/form-data
      x-accepts:
      - application/json
  /Account/Manage/DownloadPersonalData:
    post:
      responses:
        "200":
          description: OK
      tags:
      - FenixAlliance.ABS.Web
      x-accepts:
      - application/json
  /api/v2/TimeTrackerService/ProjectTimeLogs:
    get:
      description: Retrieves a list of time logs for a specific project period with
        OData query support.
      operationId: GetProjectPeriodTimeLogsAsync
      parameters:
      - explode: true
        in: query
        name: tenantId
        required: true
        schema:
          format: uuid
          type: string
        style: form
      - explode: true
        in: query
        name: projectPeriodId
        required: true
        schema:
          format: uuid
          type: string
        style: form
      - explode: true
        in: query
        name: api-version
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: header
        name: x-api-version
        required: false
        schema:
          type: string
        style: simple
      responses:
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
          description: Forbidden
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
          description: Unauthorized
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectTimeLogDtoListEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ProjectTimeLogDtoListEnvelope'
          description: OK
      summary: Retrieve project period time logs
      tags:
      - ProjectTimeLogs
      x-accepts:
      - application/json
      - application/xml
    post:
      description: Creates a new project time log entry.
      operationId: CreateProjectTimeLogAsync
      parameters:
      - explode: true
        in: query
        name: tenantId
        required: true
        schema:
          format: uuid
          type: string
        style: form
      - explode: true
        in: query
        name: api-version
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: header
        name: x-api-version
        required: false
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectTimeLogCreateDto'
          application/xml:
            schema:
              $ref: '#/components/schemas/ProjectTimeLogCreateDto'
      responses:
        "200":
          description: OK
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
          description: Forbidden
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
          description: Unauthorized
      summary: Create a new project time log
      tags:
      - ProjectTimeLogs
      x-content-type: application/json
      x-accepts:
      - application/json
      - application/xml
  /api/v2/TimeTrackerService/ProjectTimeLogs/Count:
    get:
      description: Returns the total count of time logs for a specific project period
        with OData query support.
      operationId: CountProjectPeriodTimeLogsAsync
      parameters:
      - explode: true
        in: query
        name: tenantId
        required: true
        schema:
          format: uuid
          type: string
        style: form
      - explode: true
        in: query
        name: projectPeriodId
        required: true
        schema:
          format: uuid
          type: string
        style: form
      - explode: true
        in: query
        name: api-version
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: header
        name: x-api-version
        required: false
        schema:
          type: string
        style: simple
      responses:
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
          description: Forbidden
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
          description: Unauthorized
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Int32Envelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/Int32Envelope'
          description: OK
      summary: Get the count of project period time logs
      tags:
      - ProjectTimeLogs
      x-accepts:
      - application/json
      - application/xml
  /api/v2/TimeTrackerService/ProjectTimeLogs/ByResponsibleContact:
    get:
      description: Retrieves time logs where the specified contact is the responsible
        party.
      operationId: GetProjectTimeLogsByResponsibleContactAsync
      parameters:
      - explode: true
        in: query
        name: contactId
        required: true
        schema:
          format: uuid
          type: string
        style: form
      - explode: true
        in: query
        name: tenantId
        required: true
        schema:
          format: uuid
          type: string
        style: form
      - explode: true
        in: query
        name: api-version
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: header
        name: x-api-version
        required: false
        schema:
          type: string
        style: simple
      responses:
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
          description: Forbidden
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
          description: Unauthorized
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectTimeLogDtoListEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ProjectTimeLogDtoListEnvelope'
          description: OK
      summary: Retrieve time logs by responsible contact
      tags:
      - ProjectTimeLogs
      x-accepts:
      - application/json
      - application/xml
  /api/v2/TimeTrackerService/ProjectTimeLogs/CreatedByContact:
    get:
      description: Retrieves time logs that were created by the specified contact.
      operationId: GetProjectTimeLogsCreatedByContactAsync
      parameters:
      - explode: true
        in: query
        name: contactId
        required: true
        schema:
          format: uuid
          type: string
        style: form
      - explode: true
        in: query
        name: tenantId
        required: true
        schema:
          format: uuid
          type: string
        style: form
      - explode: true
        in: query
        name: api-version
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: header
        name: x-api-version
        required: false
        schema:
          type: string
        style: simple
      responses:
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
          description: Forbidden
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
          description: Unauthorized
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectTimeLogDtoListEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ProjectTimeLogDtoListEnvelope'
          description: OK
      summary: Retrieve time logs created by a contact
      tags:
      - ProjectTimeLogs
      x-accepts:
      - application/json
      - application/xml
  /api/v2/TimeTrackerService/ProjectTimeLogs/ForProject/{projectId}:
    get:
      description: Retrieves all time logs associated with the specified project.
      operationId: GetProjectTimeLogsAsync
      parameters:
      - explode: false
        in: path
        name: projectId
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      - explode: true
        in: query
        name: tenantId
        required: true
        schema:
          format: uuid
          type: string
        style: form
      - explode: true
        in: query
        name: api-version
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: header
        name: x-api-version
        required: false
        schema:
          type: string
        style: simple
      responses:
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
          description: Forbidden
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
          description: Unauthorized
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectTimeLogDtoListEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ProjectTimeLogDtoListEnvelope'
          description: OK
      summary: Retrieve time logs for a project
      tags:
      - ProjectTimeLogs
      x-accepts:
      - application/json
      - application/xml
  /api/v2/TimeTrackerService/ProjectTimeLogs/{timeLogId}:
    delete:
      description: Deletes a project time log entry.
      operationId: DeleteProjectTimeLogAsync
      parameters:
      - explode: true
        in: query
        name: tenantId
        required: true
        schema:
          format: uuid
          type: string
        style: form
      - explode: false
        in: path
        name: timeLogId
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      - explode: true
        in: query
        name: api-version
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: header
        name: x-api-version
        required: false
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: OK
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
          description: Forbidden
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
          description: Unauthorized
      summary: Delete a project time log
      tags:
      - ProjectTimeLogs
      x-accepts:
      - application/json
      - application/xml
    get:
      description: Retrieves a single project time log by its unique identifier.
      operationId: GetProjectTimeLogByIdAsync
      parameters:
      - explode: false
        in: path
        name: timeLogId
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      - explode: true
        in: query
        name: tenantId
        required: true
        schema:
          format: uuid
          type: string
        style: form
      - explode: true
        in: query
        name: api-version
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: header
        name: x-api-version
        required: false
        schema:
          type: string
        style: simple
      responses:
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
          description: Forbidden
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
          description: Unauthorized
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectTimeLogDtoEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ProjectTimeLogDtoEnvelope'
          description: OK
      summary: Retrieve a project time log by ID
      tags:
      - ProjectTimeLogs
      x-accepts:
      - application/json
      - application/xml
    put:
      description: Updates an existing project time log entry.
      operationId: UpdateProjectTimeLogAsync
      parameters:
      - explode: false
        in: path
        name: timeLogId
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      - explode: true
        in: query
        name: tenantId
        required: true
        schema:
          format: uuid
          type: string
        style: form
      - explode: true
        in: query
        name: api-version
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: header
        name: x-api-version
        required: false
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectTimeLogUpdateDto'
          application/xml:
            schema:
              $ref: '#/components/schemas/ProjectTimeLogUpdateDto'
      responses:
        "200":
          description: OK
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
          description: Forbidden
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
          description: Unauthorized
      summary: Update a project time log
      tags:
      - ProjectTimeLogs
      x-content-type: application/json
      x-accepts:
      - application/json
      - application/xml
  /api/v2/TimeTrackerService/TimeLogApprovals:
    post:
      description: Creates a new project hours approval request.
      operationId: RequestProjectHoursApprovalAsync
      parameters:
      - explode: true
        in: query
        name: tenantId
        required: true
        schema:
          format: uuid
          type: string
        style: form
      - explode: true
        in: query
        name: api-version
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: header
        name: x-api-version
        required: false
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectHoursApprovalCreateDto'
          application/xml:
            schema:
              $ref: '#/components/schemas/ProjectHoursApprovalCreateDto'
      responses:
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
          description: Forbidden
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
          description: Unauthorized
        "200":
          description: OK
      summary: Request project hours approval
      tags:
      - TimeLogApprovals
      x-content-type: application/json
      x-accepts:
      - application/json
      - application/xml
  /api/v2/TimeTrackerService/TimeLogApprovals/{approvalId}/Status:
    put:
      description: Updates the status of an existing project hours approval.
      operationId: UpdateProjectHoursApprovalStatusAsync
      parameters:
      - explode: true
        in: query
        name: tenantId
        required: true
        schema:
          format: uuid
          type: string
        style: form
      - explode: false
        in: path
        name: approvalId
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      - explode: true
        in: query
        name: api-version
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: header
        name: x-api-version
        required: false
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectHoursApprovalStatusUpdateDto'
          application/xml:
            schema:
              $ref: '#/components/schemas/ProjectHoursApprovalStatusUpdateDto'
      responses:
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
          description: Forbidden
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
          description: Unauthorized
        "200":
          description: OK
      summary: Update approval status
      tags:
      - TimeLogApprovals
      x-content-type: application/json
      x-accepts:
      - application/json
      - application/xml
  /api/v2/TimeTrackerService/TimeLogApprovals/{approvalId}/Approver:
    put:
      description: Updates the approver of an existing project hours approval.
      operationId: UpdateProjectHoursApprovalApproverAsync
      parameters:
      - explode: false
        in: path
        name: approvalId
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      - explode: true
        in: query
        name: tenantId
        required: true
        schema:
          format: uuid
          type: string
        style: form
      - explode: true
        in: query
        name: api-version
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: header
        name: x-api-version
        required: false
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectHoursApprovalApproverUpdateDto'
          application/xml:
            schema:
              $ref: '#/components/schemas/ProjectHoursApprovalApproverUpdateDto'
      responses:
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
          description: Forbidden
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
          description: Unauthorized
        "200":
          description: OK
      summary: Update approval approver
      tags:
      - TimeLogApprovals
      x-content-type: application/json
      x-accepts:
      - application/json
      - application/xml
components:
  schemas:
    AccessTokenResponse:
      additionalProperties: false
      example:
        expiresIn: 0
        tokenType: tokenType
        accessToken: accessToken
        refreshToken: refreshToken
      properties:
        tokenType:
          nullable: true
          readOnly: true
          type: string
        accessToken:
          nullable: true
          type: string
        expiresIn:
          format: int64
          type: integer
        refreshToken:
          nullable: true
          type: string
      required:
      - accessToken
      - expiresIn
      - refreshToken
      type: object
    ErrorEnvelope:
      additionalProperties: false
      example:
        activityId: activityId
        errorMessage: errorMessage
        correlationId: correlationId
        isSuccess: true
        timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        isSuccess:
          readOnly: true
          type: boolean
        errorMessage:
          nullable: true
          type: string
        correlationId:
          nullable: true
          type: string
        timestamp:
          format: date-time
          readOnly: true
          type: string
        activityId:
          nullable: true
          readOnly: true
          type: string
      type: object
    ForgotPasswordRequest:
      additionalProperties: false
      example:
        email: email
      properties:
        email:
          nullable: true
          type: string
      required:
      - email
      type: object
    HttpValidationProblemDetails:
      additionalProperties: {}
      properties:
        type:
          nullable: true
          type: string
        title:
          nullable: true
          type: string
        status:
          format: int32
          nullable: true
          type: integer
        detail:
          nullable: true
          type: string
        instance:
          nullable: true
          type: string
        errors:
          additionalProperties:
            items:
              type: string
            type: array
          nullable: true
          type: object
      type: object
    InfoRequest:
      additionalProperties: false
      example:
        oldPassword: oldPassword
        newPassword: newPassword
        newEmail: newEmail
      properties:
        newEmail:
          nullable: true
          type: string
        newPassword:
          nullable: true
          type: string
        oldPassword:
          nullable: true
          type: string
      type: object
    InfoResponse:
      additionalProperties: false
      example:
        email: email
        isEmailConfirmed: true
      properties:
        email:
          nullable: true
          type: string
        isEmailConfirmed:
          type: boolean
      required:
      - email
      - isEmailConfirmed
      type: object
    Int32Envelope:
      additionalProperties: false
      example:
        result: 0
        activityId: activityId
        errorMessage: errorMessage
        correlationId: correlationId
        isSuccess: true
        timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        isSuccess:
          readOnly: true
          type: boolean
        errorMessage:
          nullable: true
          type: string
        correlationId:
          nullable: true
          type: string
        timestamp:
          format: date-time
          readOnly: true
          type: string
        activityId:
          nullable: true
          readOnly: true
          type: string
        result:
          format: int32
          type: integer
      type: object
    LoginRequest:
      additionalProperties: false
      example:
        password: password
        twoFactorRecoveryCode: twoFactorRecoveryCode
        email: email
        twoFactorCode: twoFactorCode
      properties:
        email:
          nullable: true
          type: string
        password:
          nullable: true
          type: string
        twoFactorCode:
          nullable: true
          type: string
        twoFactorRecoveryCode:
          nullable: true
          type: string
      required:
      - email
      - password
      type: object
    ProjectHoursApprovalApproverUpdateDto:
      additionalProperties: false
      example:
        approverContactID: approverContactID
      properties:
        approverContactID:
          nullable: true
          type: string
      type: object
    ProjectHoursApprovalCreateDto:
      additionalProperties: false
      example:
        comments: comments
        approverContactID: approverContactID
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        projectPeriodID: projectPeriodID
        timestamp: 2000-01-23T04:56:07.000+00:00
        requesterContactID: requesterContactID
      properties:
        id:
          format: uuid
          type: string
        timestamp:
          format: date-time
          type: string
        requesterContactID:
          nullable: true
          type: string
        approverContactID:
          nullable: true
          type: string
        projectPeriodID:
          nullable: true
          type: string
        comments:
          nullable: true
          type: string
      type: object
    ProjectHoursApprovalStatusUpdateDto:
      additionalProperties: false
      example:
        approvalStatus: Pending
        comments: comments
      properties:
        approvalStatus:
          enum:
          - Pending
          - Approved
          - Rejected
          type: string
        comments:
          nullable: true
          type: string
      type: object
    ProjectTimeLogCreateDto:
      additionalProperties: false
      example:
        projectTaskID: projectTaskID
        comments: comments
        logDate: 2000-01-23T04:56:07.000+00:00
        projectTimeLogRecordType: RegularHours
        timeSpan: timeSpan
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        projectID: projectID
        projectPeriodID: projectPeriodID
        timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        id:
          format: uuid
          type: string
        timestamp:
          format: date-time
          type: string
        timeSpan:
          format: date-span
          type: string
        logDate:
          format: date-time
          type: string
        comments:
          nullable: true
          type: string
        projectTaskID:
          minLength: 1
          type: string
        projectPeriodID:
          minLength: 1
          type: string
        projectTimeLogRecordType:
          enum:
          - RegularHours
          - OvertimeToPay
          - OvertimeToCompensate
          type: string
        projectID:
          nullable: true
          type: string
      required:
      - projectPeriodID
      - projectTaskID
      type: object
    ProjectTimeLogDto:
      additionalProperties: false
      example:
        comments: comments
        logDate: 2000-01-23T04:56:07.000+00:00
        recordType: RegularHours
        type: type
        projectPeriodId: projectPeriodId
        projectTaskId: projectTaskId
        responsibleContactId: responsibleContactId
        timeSpan: timeSpan
        id: id
        taskCategoryId: taskCategoryId
        projectId: projectId
        creatorContactId: creatorContactId
        timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        id:
          nullable: true
          type: string
        timestamp:
          format: date-time
          nullable: true
          type: string
        projectId:
          nullable: true
          type: string
        projectTaskId:
          nullable: true
          type: string
        taskCategoryId:
          nullable: true
          type: string
        projectPeriodId:
          nullable: true
          type: string
        responsibleContactId:
          nullable: true
          type: string
        creatorContactId:
          nullable: true
          type: string
        recordType:
          enum:
          - RegularHours
          - OvertimeToPay
          - OvertimeToCompensate
          type: string
        timeSpan:
          format: date-span
          type: string
        logDate:
          format: date-time
          type: string
        comments:
          nullable: true
          type: string
        type:
          nullable: true
          type: string
      type: object
    ProjectTimeLogDtoEnvelope:
      additionalProperties: false
      example:
        result:
          comments: comments
          logDate: 2000-01-23T04:56:07.000+00:00
          recordType: RegularHours
          type: type
          projectPeriodId: projectPeriodId
          projectTaskId: projectTaskId
          responsibleContactId: responsibleContactId
          timeSpan: timeSpan
          id: id
          taskCategoryId: taskCategoryId
          projectId: projectId
          creatorContactId: creatorContactId
          timestamp: 2000-01-23T04:56:07.000+00:00
        activityId: activityId
        errorMessage: errorMessage
        correlationId: correlationId
        isSuccess: true
        timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        isSuccess:
          readOnly: true
          type: boolean
        errorMessage:
          nullable: true
          type: string
        correlationId:
          nullable: true
          type: string
        timestamp:
          format: date-time
          readOnly: true
          type: string
        activityId:
          nullable: true
          readOnly: true
          type: string
        result:
          $ref: '#/components/schemas/ProjectTimeLogDto'
      type: object
    ProjectTimeLogDtoListEnvelope:
      additionalProperties: false
      example:
        result:
        - comments: comments
          logDate: 2000-01-23T04:56:07.000+00:00
          recordType: RegularHours
          type: type
          projectPeriodId: projectPeriodId
          projectTaskId: projectTaskId
          responsibleContactId: responsibleContactId
          timeSpan: timeSpan
          id: id
          taskCategoryId: taskCategoryId
          projectId: projectId
          creatorContactId: creatorContactId
          timestamp: 2000-01-23T04:56:07.000+00:00
        - comments: comments
          logDate: 2000-01-23T04:56:07.000+00:00
          recordType: RegularHours
          type: type
          projectPeriodId: projectPeriodId
          projectTaskId: projectTaskId
          responsibleContactId: responsibleContactId
          timeSpan: timeSpan
          id: id
          taskCategoryId: taskCategoryId
          projectId: projectId
          creatorContactId: creatorContactId
          timestamp: 2000-01-23T04:56:07.000+00:00
        activityId: activityId
        errorMessage: errorMessage
        correlationId: correlationId
        isSuccess: true
        timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        isSuccess:
          readOnly: true
          type: boolean
        errorMessage:
          nullable: true
          type: string
        correlationId:
          nullable: true
          type: string
        timestamp:
          format: date-time
          readOnly: true
          type: string
        activityId:
          nullable: true
          readOnly: true
          type: string
        result:
          items:
            $ref: '#/components/schemas/ProjectTimeLogDto'
          nullable: true
          type: array
      type: object
    ProjectTimeLogUpdateDto:
      additionalProperties: false
      example:
        projectTaskID: projectTaskID
        comments: comments
        logDate: 2000-01-23T04:56:07.000+00:00
        projectTimeLogRecordType: RegularHours
        timeSpan: timeSpan
        projectPeriodID: projectPeriodID
      properties:
        logDate:
          format: date-time
          type: string
        timeSpan:
          format: date-span
          type: string
        comments:
          nullable: true
          type: string
        projectTaskID:
          nullable: true
          type: string
        projectPeriodID:
          nullable: true
          type: string
        projectTimeLogRecordType:
          enum:
          - RegularHours
          - OvertimeToPay
          - OvertimeToCompensate
          type: string
      type: object
    RefreshRequest:
      additionalProperties: false
      example:
        refreshToken: refreshToken
      properties:
        refreshToken:
          nullable: true
          type: string
      required:
      - refreshToken
      type: object
    RegisterRequest:
      additionalProperties: false
      example:
        password: password
        email: email
      properties:
        email:
          nullable: true
          type: string
        password:
          nullable: true
          type: string
      required:
      - email
      - password
      type: object
    ResendConfirmationEmailRequest:
      additionalProperties: false
      example:
        email: email
      properties:
        email:
          nullable: true
          type: string
      required:
      - email
      type: object
    ResetPasswordRequest:
      additionalProperties: false
      example:
        resetCode: resetCode
        newPassword: newPassword
        email: email
      properties:
        email:
          nullable: true
          type: string
        resetCode:
          nullable: true
          type: string
        newPassword:
          nullable: true
          type: string
      required:
      - email
      - newPassword
      - resetCode
      type: object
    TwoFactorRequest:
      additionalProperties: false
      example:
        resetRecoveryCodes: true
        enable: true
        resetSharedKey: true
        forgetMachine: true
        twoFactorCode: twoFactorCode
      properties:
        enable:
          nullable: true
          type: boolean
        twoFactorCode:
          nullable: true
          type: string
        resetSharedKey:
          type: boolean
        resetRecoveryCodes:
          type: boolean
        forgetMachine:
          type: boolean
      type: object
    TwoFactorResponse:
      additionalProperties: false
      example:
        sharedKey: sharedKey
        isTwoFactorEnabled: true
        isMachineRemembered: true
        recoveryCodesLeft: 0
        recoveryCodes:
        - recoveryCodes
        - recoveryCodes
      properties:
        sharedKey:
          nullable: true
          type: string
        recoveryCodesLeft:
          format: int32
          type: integer
        recoveryCodes:
          items:
            type: string
          nullable: true
          type: array
        isTwoFactorEnabled:
          type: boolean
        isMachineRemembered:
          type: boolean
      required:
      - isMachineRemembered
      - isTwoFactorEnabled
      - recoveryCodesLeft
      - sharedKey
      type: object
    _Account_PerformExternalLogin_post_request:
      properties:
        provider:
          type: string
        returnUrl:
          type: string
      type: object
    _Account_Logout_post_request:
      properties:
        returnUrl:
          type: string
      type: object
    _Account_Manage_LinkExternalLogin_post_request:
      properties:
        provider:
          type: string
      type: object

