openapi: 3.0.4
info:
  contact:
    email: support@fenix-alliance.com
    name: Fenix Alliance Inc.
    url: https://fenixalliance.com.co/Support
  license:
    name: Fenix Alliance Inc.
    url: https://fenix-alliance.com.co/Legal/Policies/eula
  termsOfService: https://absuite.net/eula
  title: InventoryService
  version: 2.1.2.5401
servers:
- url: /
tags:
- name: Completions
- name: FenixAlliance.Portals.Website
- name: Inventory
paths:
  /api/v2/AiService/Completions/Complete:
    get:
      parameters:
      - explode: true
        in: query
        name: tenantId
        required: true
        schema:
          format: uuid
          type: string
        style: form
      - explode: true
        in: query
        name: conversationId
        required: false
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: message
        required: false
        schema:
          type: string
        style: form
      responses:
        "403":
          content:
            application/json;odata.metadata=minimal;odata.streaming=true:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=minimal;odata.streaming=false:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=minimal:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=full;odata.streaming=true:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=full;odata.streaming=false:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=full:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=none;odata.streaming=true:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=none;odata.streaming=false:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=none:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.streaming=true:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.streaming=false:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=true:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=minimal;odata.streaming=false;IEEE754Compatible=false:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=minimal;odata.streaming=false;IEEE754Compatible=true:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=minimal;IEEE754Compatible=false:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=minimal;IEEE754Compatible=true:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=full;odata.streaming=true;IEEE754Compatible=false:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=full;odata.streaming=true;IEEE754Compatible=true:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=full;odata.streaming=false;IEEE754Compatible=false:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=full;odata.streaming=false;IEEE754Compatible=true:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=full;IEEE754Compatible=false:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=full;IEEE754Compatible=true:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=none;odata.streaming=true;IEEE754Compatible=false:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=none;odata.streaming=true;IEEE754Compatible=true:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=none;odata.streaming=false;IEEE754Compatible=true:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=none;odata.streaming=false;IEEE754Compatible=false:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=none;IEEE754Compatible=false:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=none;IEEE754Compatible=true:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.streaming=true;IEEE754Compatible=false:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.streaming=true;IEEE754Compatible=true:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.streaming=false;IEEE754Compatible=false:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.streaming=false;IEEE754Compatible=true:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;IEEE754Compatible=false:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;IEEE754Compatible=true:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            text/plain:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            text/json:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            text/xml:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
          description: Forbidden
        "401":
          content:
            application/json;odata.metadata=minimal;odata.streaming=true:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=minimal;odata.streaming=false:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=minimal:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=full;odata.streaming=true:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=full;odata.streaming=false:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=full:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=none;odata.streaming=true:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=none;odata.streaming=false:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=none:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.streaming=true:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.streaming=false:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=true:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=minimal;odata.streaming=false;IEEE754Compatible=false:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=minimal;odata.streaming=false;IEEE754Compatible=true:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=minimal;IEEE754Compatible=false:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=minimal;IEEE754Compatible=true:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=full;odata.streaming=true;IEEE754Compatible=false:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=full;odata.streaming=true;IEEE754Compatible=true:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=full;odata.streaming=false;IEEE754Compatible=false:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=full;odata.streaming=false;IEEE754Compatible=true:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=full;IEEE754Compatible=false:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=full;IEEE754Compatible=true:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=none;odata.streaming=true;IEEE754Compatible=false:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=none;odata.streaming=true;IEEE754Compatible=true:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=none;odata.streaming=false;IEEE754Compatible=true:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=none;odata.streaming=false;IEEE754Compatible=false:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=none;IEEE754Compatible=false:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.metadata=none;IEEE754Compatible=true:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.streaming=true;IEEE754Compatible=false:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.streaming=true;IEEE754Compatible=true:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.streaming=false;IEEE754Compatible=false:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;odata.streaming=false;IEEE754Compatible=true:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;IEEE754Compatible=false:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/json;IEEE754Compatible=true:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            text/plain:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            text/json:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            text/xml:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
          description: Unauthorized
        "200":
          description: OK
      tags:
      - Completions
      x-accepts:
      - application/json
      - application/json;IEEE754Compatible=false
      - application/json;IEEE754Compatible=true
      - application/json;odata.metadata=full
      - application/json;odata.metadata=full;IEEE754Compatible=false
      - application/json;odata.metadata=full;IEEE754Compatible=true
      - application/json;odata.metadata=full;odata.streaming=false
      - application/json;odata.metadata=full;odata.streaming=false;IEEE754Compatible=false
      - application/json;odata.metadata=full;odata.streaming=false;IEEE754Compatible=true
      - application/json;odata.metadata=full;odata.streaming=true
      - application/json;odata.metadata=full;odata.streaming=true;IEEE754Compatible=false
      - application/json;odata.metadata=full;odata.streaming=true;IEEE754Compatible=true
      - application/json;odata.metadata=minimal
      - application/json;odata.metadata=minimal;IEEE754Compatible=false
      - application/json;odata.metadata=minimal;IEEE754Compatible=true
      - application/json;odata.metadata=minimal;odata.streaming=false
      - application/json;odata.metadata=minimal;odata.streaming=false;IEEE754Compatible=false
      - application/json;odata.metadata=minimal;odata.streaming=false;IEEE754Compatible=true
      - application/json;odata.metadata=minimal;odata.streaming=true
      - application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false
      - application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=true
      - application/json;odata.metadata=none
      - application/json;odata.metadata=none;IEEE754Compatible=false
      - application/json;odata.metadata=none;IEEE754Compatible=true
      - application/json;odata.metadata=none;odata.streaming=false
      - application/json;odata.metadata=none;odata.streaming=false;IEEE754Compatible=false
      - application/json;odata.metadata=none;odata.streaming=false;IEEE754Compatible=true
      - application/json;odata.metadata=none;odata.streaming=true
      - application/json;odata.metadata=none;odata.streaming=true;IEEE754Compatible=false
      - application/json;odata.metadata=none;odata.streaming=true;IEEE754Compatible=true
      - application/json;odata.streaming=false
      - application/json;odata.streaming=false;IEEE754Compatible=false
      - application/json;odata.streaming=false;IEEE754Compatible=true
      - application/json;odata.streaming=true
      - application/json;odata.streaming=true;IEEE754Compatible=false
      - application/json;odata.streaming=true;IEEE754Compatible=true
      - application/octet-stream
      - application/xml
      - text/json
      - text/plain
      - text/xml
  /version:
    get:
      responses:
        "200":
          description: OK
      tags:
      - FenixAlliance.Portals.Website
      x-accepts:
      - application/json
  /health:
    get:
      responses:
        "200":
          description: OK
      tags:
      - FenixAlliance.Portals.Website
      x-accepts:
      - application/json
  /hello:
    get:
      responses:
        "200":
          description: OK
      tags:
      - FenixAlliance.Portals.Website
      x-accepts:
      - application/json
  /register:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
        required: true
      responses:
        "200":
          description: OK
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
          description: Bad Request
      tags:
      - FenixAlliance.Portals.Website
      x-content-type: application/json
      x-accepts:
      - application/problem+json
  /login:
    post:
      parameters:
      - explode: true
        in: query
        name: useCookies
        required: false
        schema:
          type: boolean
        style: form
      - explode: true
        in: query
        name: useSessionCookies
        required: false
        schema:
          type: boolean
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessTokenResponse'
          description: OK
      tags:
      - FenixAlliance.Portals.Website
      x-content-type: application/json
      x-accepts:
      - application/json
  /refresh:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessTokenResponse'
          description: OK
      tags:
      - FenixAlliance.Portals.Website
      x-content-type: application/json
      x-accepts:
      - application/json
  /confirmEmail:
    get:
      operationId: MapIdentityApi-/confirmEmail
      parameters:
      - explode: true
        in: query
        name: userId
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: code
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: changedEmail
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          description: OK
      tags:
      - FenixAlliance.Portals.Website
      x-accepts:
      - application/json
  /resendConfirmationEmail:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResendConfirmationEmailRequest'
        required: true
      responses:
        "200":
          description: OK
      tags:
      - FenixAlliance.Portals.Website
      x-content-type: application/json
      x-accepts:
      - application/json
  /forgotPassword:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ForgotPasswordRequest'
        required: true
      responses:
        "200":
          description: OK
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
          description: Bad Request
      tags:
      - FenixAlliance.Portals.Website
      x-content-type: application/json
      x-accepts:
      - application/problem+json
  /resetPassword:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPasswordRequest'
        required: true
      responses:
        "200":
          description: OK
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
          description: Bad Request
      tags:
      - FenixAlliance.Portals.Website
      x-content-type: application/json
      x-accepts:
      - application/problem+json
  /manage/2fa:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TwoFactorRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TwoFactorResponse'
          description: OK
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
          description: Bad Request
        "404":
          description: Not Found
      tags:
      - FenixAlliance.Portals.Website
      x-content-type: application/json
      x-accepts:
      - application/json
      - application/problem+json
  /manage/info:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InfoResponse'
          description: OK
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
          description: Bad Request
        "404":
          description: Not Found
      tags:
      - FenixAlliance.Portals.Website
      x-accepts:
      - application/json
      - application/problem+json
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InfoRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InfoResponse'
          description: OK
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
          description: Bad Request
        "404":
          description: Not Found
      tags:
      - FenixAlliance.Portals.Website
      x-content-type: application/json
      x-accepts:
      - application/json
      - application/problem+json
  /Account/PerformExternalLogin:
    post:
      requestBody:
        content:
          multipart/form-data:
            encoding:
              provider:
                style: form
              returnUrl:
                style: form
            schema:
              $ref: '#/components/schemas/_Account_PerformExternalLogin_post_request'
          application/x-www-form-urlencoded:
            encoding:
              provider:
                style: form
              returnUrl:
                style: form
            schema:
              $ref: '#/components/schemas/_Account_PerformExternalLogin_post_request'
      responses:
        "200":
          description: OK
      tags:
      - FenixAlliance.Portals.Website
      x-content-type: multipart/form-data
      x-accepts:
      - application/json
  /Account/Logout:
    post:
      requestBody:
        content:
          multipart/form-data:
            encoding:
              returnUrl:
                style: form
            schema:
              $ref: '#/components/schemas/_Account_Logout_post_request'
          application/x-www-form-urlencoded:
            encoding:
              returnUrl:
                style: form
            schema:
              $ref: '#/components/schemas/_Account_Logout_post_request'
      responses:
        "200":
          description: OK
      tags:
      - FenixAlliance.Portals.Website
      x-content-type: multipart/form-data
      x-accepts:
      - application/json
  /Account/Manage/LinkExternalLogin:
    post:
      requestBody:
        content:
          multipart/form-data:
            encoding:
              provider:
                style: form
            schema:
              $ref: '#/components/schemas/_Account_Manage_LinkExternalLogin_post_request'
          application/x-www-form-urlencoded:
            encoding:
              provider:
                style: form
            schema:
              $ref: '#/components/schemas/_Account_Manage_LinkExternalLogin_post_request'
      responses:
        "200":
          description: OK
      tags:
      - FenixAlliance.Portals.Website
      x-content-type: multipart/form-data
      x-accepts:
      - application/json
  /Account/Manage/DownloadPersonalData:
    post:
      responses:
        "200":
          description: OK
      tags:
      - FenixAlliance.Portals.Website
      x-accepts:
      - application/json
  /api/v2/InventoryService/Inventory/{stockItemId}/Details:
    get:
      description: Retrieves the inventory details for a specific stock item by its
        ID.
      operationId: GetInventoryDetailsAsync
      parameters:
      - explode: false
        in: path
        name: stockItemId
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      - explode: true
        in: query
        name: api-version
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: header
        name: x-api-version
        required: false
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: OK
      summary: Get inventory details for a stock item
      tags:
      - Inventory
      x-accepts:
      - application/json
components:
  schemas:
    AccessTokenResponse:
      additionalProperties: false
      example:
        expiresIn: 0
        tokenType: tokenType
        accessToken: accessToken
        refreshToken: refreshToken
      properties:
        tokenType:
          nullable: true
          readOnly: true
          type: string
        accessToken:
          nullable: true
          type: string
        expiresIn:
          format: int64
          type: integer
        refreshToken:
          nullable: true
          type: string
      required:
      - accessToken
      - expiresIn
      - refreshToken
      type: object
    ErrorEnvelope:
      additionalProperties: false
      example:
        activityId: activityId
        errorMessage: errorMessage
        correlationId: correlationId
        isSuccess: true
        timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        isSuccess:
          readOnly: true
          type: boolean
        errorMessage:
          nullable: true
          type: string
        correlationId:
          nullable: true
          type: string
        timestamp:
          format: date-time
          readOnly: true
          type: string
        activityId:
          nullable: true
          readOnly: true
          type: string
      type: object
    ForgotPasswordRequest:
      additionalProperties: false
      example:
        email: email
      properties:
        email:
          nullable: true
          type: string
      required:
      - email
      type: object
    HttpValidationProblemDetails:
      additionalProperties: {}
      properties:
        type:
          nullable: true
          type: string
        title:
          nullable: true
          type: string
        status:
          format: int32
          nullable: true
          type: integer
        detail:
          nullable: true
          type: string
        instance:
          nullable: true
          type: string
        errors:
          additionalProperties:
            items:
              type: string
            type: array
          nullable: true
          type: object
      type: object
    InfoRequest:
      additionalProperties: false
      example:
        oldPassword: oldPassword
        newPassword: newPassword
        newEmail: newEmail
      properties:
        newEmail:
          nullable: true
          type: string
        newPassword:
          nullable: true
          type: string
        oldPassword:
          nullable: true
          type: string
      type: object
    InfoResponse:
      additionalProperties: false
      example:
        email: email
        isEmailConfirmed: true
      properties:
        email:
          nullable: true
          type: string
        isEmailConfirmed:
          type: boolean
      required:
      - email
      - isEmailConfirmed
      type: object
    LoginRequest:
      additionalProperties: false
      example:
        password: password
        twoFactorRecoveryCode: twoFactorRecoveryCode
        email: email
        twoFactorCode: twoFactorCode
      properties:
        email:
          nullable: true
          type: string
        password:
          nullable: true
          type: string
        twoFactorCode:
          nullable: true
          type: string
        twoFactorRecoveryCode:
          nullable: true
          type: string
      required:
      - email
      - password
      type: object
    RefreshRequest:
      additionalProperties: false
      example:
        refreshToken: refreshToken
      properties:
        refreshToken:
          nullable: true
          type: string
      required:
      - refreshToken
      type: object
    RegisterRequest:
      additionalProperties: false
      example:
        password: password
        email: email
      properties:
        email:
          nullable: true
          type: string
        password:
          nullable: true
          type: string
      required:
      - email
      - password
      type: object
    ResendConfirmationEmailRequest:
      additionalProperties: false
      example:
        email: email
      properties:
        email:
          nullable: true
          type: string
      required:
      - email
      type: object
    ResetPasswordRequest:
      additionalProperties: false
      example:
        resetCode: resetCode
        newPassword: newPassword
        email: email
      properties:
        email:
          nullable: true
          type: string
        resetCode:
          nullable: true
          type: string
        newPassword:
          nullable: true
          type: string
      required:
      - email
      - newPassword
      - resetCode
      type: object
    TwoFactorRequest:
      additionalProperties: false
      example:
        resetRecoveryCodes: true
        enable: true
        resetSharedKey: true
        forgetMachine: true
        twoFactorCode: twoFactorCode
      properties:
        enable:
          nullable: true
          type: boolean
        twoFactorCode:
          nullable: true
          type: string
        resetSharedKey:
          type: boolean
        resetRecoveryCodes:
          type: boolean
        forgetMachine:
          type: boolean
      type: object
    TwoFactorResponse:
      additionalProperties: false
      example:
        sharedKey: sharedKey
        isTwoFactorEnabled: true
        isMachineRemembered: true
        recoveryCodesLeft: 0
        recoveryCodes:
        - recoveryCodes
        - recoveryCodes
      properties:
        sharedKey:
          nullable: true
          type: string
        recoveryCodesLeft:
          format: int32
          type: integer
        recoveryCodes:
          items:
            type: string
          nullable: true
          type: array
        isTwoFactorEnabled:
          type: boolean
        isMachineRemembered:
          type: boolean
      required:
      - isMachineRemembered
      - isTwoFactorEnabled
      - recoveryCodesLeft
      - sharedKey
      type: object
    _Account_PerformExternalLogin_post_request:
      properties:
        provider:
          type: string
        returnUrl:
          type: string
      type: object
    _Account_Logout_post_request:
      properties:
        returnUrl:
          type: string
      type: object
    _Account_Manage_LinkExternalLogin_post_request:
      properties:
        provider:
          type: string
      type: object

