openapi: 3.0.4
info:
  contact:
    email: support@fenix-alliance.com
    name: Fenix Alliance Inc.
    url: https://fenixalliance.com.co/Support
  license:
    name: Fenix Alliance Inc.
    url: https://fenix-alliance.com.co/Legal/Policies/eula
  termsOfService: https://absuite.net/eula
  title: LogisticsService
  version: 2.0.0.0
servers:
- description: Alliance Business Suite API
  url: "{server}"
  variables:
    server:
      default: https://absuite.net
      description: ABS instance base URL
      enum:
      - https://absuite.net
      - https://test.absuite.net
      - https://dev.absuite.net
      - https://localhost:44388
tags:
- name: FenixAlliance.ABS.Web
- name: Stock
paths:
  /version:
    get:
      responses:
        "200":
          description: OK
      tags:
      - FenixAlliance.ABS.Web
      x-accepts:
      - application/json
  /health:
    get:
      responses:
        "200":
          description: OK
      tags:
      - FenixAlliance.ABS.Web
      x-accepts:
      - application/json
  /hello:
    get:
      responses:
        "200":
          description: OK
      tags:
      - FenixAlliance.ABS.Web
      x-accepts:
      - application/json
  /register:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
        required: true
      responses:
        "200":
          description: OK
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
          description: Bad Request
      tags:
      - FenixAlliance.ABS.Web
      x-content-type: application/json
      x-accepts:
      - application/problem+json
  /login:
    post:
      parameters:
      - explode: true
        in: query
        name: useCookies
        required: false
        schema:
          type: boolean
        style: form
      - explode: true
        in: query
        name: useSessionCookies
        required: false
        schema:
          type: boolean
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessTokenResponse'
          description: OK
      tags:
      - FenixAlliance.ABS.Web
      x-content-type: application/json
      x-accepts:
      - application/json
  /refresh:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessTokenResponse'
          description: OK
      tags:
      - FenixAlliance.ABS.Web
      x-content-type: application/json
      x-accepts:
      - application/json
  /confirmEmail:
    get:
      operationId: MapIdentityApi-/confirmEmail
      parameters:
      - explode: true
        in: query
        name: userId
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: code
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: changedEmail
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          description: OK
      tags:
      - FenixAlliance.ABS.Web
      x-accepts:
      - application/json
  /resendConfirmationEmail:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResendConfirmationEmailRequest'
        required: true
      responses:
        "200":
          description: OK
      tags:
      - FenixAlliance.ABS.Web
      x-content-type: application/json
      x-accepts:
      - application/json
  /forgotPassword:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ForgotPasswordRequest'
        required: true
      responses:
        "200":
          description: OK
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
          description: Bad Request
      tags:
      - FenixAlliance.ABS.Web
      x-content-type: application/json
      x-accepts:
      - application/problem+json
  /resetPassword:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPasswordRequest'
        required: true
      responses:
        "200":
          description: OK
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
          description: Bad Request
      tags:
      - FenixAlliance.ABS.Web
      x-content-type: application/json
      x-accepts:
      - application/problem+json
  /manage/2fa:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TwoFactorRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TwoFactorResponse'
          description: OK
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
          description: Bad Request
        "404":
          description: Not Found
      tags:
      - FenixAlliance.ABS.Web
      x-content-type: application/json
      x-accepts:
      - application/json
      - application/problem+json
  /manage/info:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InfoResponse'
          description: OK
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
          description: Bad Request
        "404":
          description: Not Found
      tags:
      - FenixAlliance.ABS.Web
      x-accepts:
      - application/json
      - application/problem+json
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InfoRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InfoResponse'
          description: OK
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
          description: Bad Request
        "404":
          description: Not Found
      tags:
      - FenixAlliance.ABS.Web
      x-content-type: application/json
      x-accepts:
      - application/json
      - application/problem+json
  /Account/PerformExternalLogin:
    post:
      requestBody:
        content:
          multipart/form-data:
            encoding:
              provider:
                style: form
              returnUrl:
                style: form
            schema:
              $ref: '#/components/schemas/_Account_PerformExternalLogin_post_request'
          application/x-www-form-urlencoded:
            encoding:
              provider:
                style: form
              returnUrl:
                style: form
            schema:
              $ref: '#/components/schemas/_Account_PerformExternalLogin_post_request'
      responses:
        "200":
          description: OK
      tags:
      - FenixAlliance.ABS.Web
      x-content-type: multipart/form-data
      x-accepts:
      - application/json
  /Account/Logout:
    post:
      requestBody:
        content:
          multipart/form-data:
            encoding:
              returnUrl:
                style: form
            schema:
              $ref: '#/components/schemas/_Account_Logout_post_request'
          application/x-www-form-urlencoded:
            encoding:
              returnUrl:
                style: form
            schema:
              $ref: '#/components/schemas/_Account_Logout_post_request'
      responses:
        "200":
          description: OK
      tags:
      - FenixAlliance.ABS.Web
      x-content-type: multipart/form-data
      x-accepts:
      - application/json
  /Account/Manage/LinkExternalLogin:
    post:
      requestBody:
        content:
          multipart/form-data:
            encoding:
              provider:
                style: form
            schema:
              $ref: '#/components/schemas/_Account_Manage_LinkExternalLogin_post_request'
          application/x-www-form-urlencoded:
            encoding:
              provider:
                style: form
            schema:
              $ref: '#/components/schemas/_Account_Manage_LinkExternalLogin_post_request'
      responses:
        "200":
          description: OK
      tags:
      - FenixAlliance.ABS.Web
      x-content-type: multipart/form-data
      x-accepts:
      - application/json
  /Account/Manage/DownloadPersonalData:
    post:
      responses:
        "200":
          description: OK
      tags:
      - FenixAlliance.ABS.Web
      x-accepts:
      - application/json
  /api/v2/LogisticsService/Stock:
    get:
      description: Retrieves all business-owned contacts related to stock and logistics
        for the specified tenant.
      operationId: GetContactsAsync
      parameters:
      - explode: true
        in: query
        name: tenantId
        required: true
        schema:
          format: uuid
          type: string
        style: form
      - explode: true
        in: query
        name: api-version
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: header
        name: x-api-version
        required: false
        schema:
          type: string
        style: simple
      responses:
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
          description: Forbidden
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
          description: Unauthorized
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactDtoListEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ContactDtoListEnvelope'
          description: OK
      summary: Get all stock-related contacts
      tags:
      - Stock
      x-accepts:
      - application/json
      - application/xml
components:
  schemas:
    AccessTokenResponse:
      additionalProperties: false
      example:
        expiresIn: 0
        tokenType: tokenType
        accessToken: accessToken
        refreshToken: refreshToken
      properties:
        tokenType:
          nullable: true
          readOnly: true
          type: string
        accessToken:
          nullable: true
          type: string
        expiresIn:
          format: int64
          type: integer
        refreshToken:
          nullable: true
          type: string
      required:
      - accessToken
      - expiresIn
      - refreshToken
      type: object
    ContactDto:
      additionalProperties: false
      example:
        streetLine2: streetLine2
        zipCode: zipCode
        streetLine1: streetLine1
        jobTitle: jobTitle
        twitterUrl: https://openapi-generator.tech
        postalCode: postalCode
        tikTokUrl: https://openapi-generator.tech
        about: about
        cityId: cityId
        type: Individual
        identityProvider: identityProvider
        publicName: publicName
        id: id
        currencyId: currencyId
        gitHubUrl: https://openapi-generator.tech
        walletId: walletId
        enrollmentId: enrollmentId
        parentContactId: parentContactId
        activeDirectoryId: activeDirectoryId
        linkedInUrl: https://openapi-generator.tech
        avatarUrl: avatarUrl
        qualifiedName: qualifiedName
        cartId: cartId
        relatedTenantId: relatedTenantId
        twitchUrl: https://openapi-generator.tech
        ownerContactId: ownerContactId
        coverUrl: coverUrl
        firstName: firstName
        activityFeedId: activityFeedId
        mobilePhone: mobilePhone
        phone: phone
        webUrl: https://openapi-generator.tech
        taxId: taxId
        duns: duns
        businessPhone: businessPhone
        youTubeUrl: https://openapi-generator.tech
        annualRevenue: annualRevenue
        birthday: 2000-01-23T04:56:07.000+00:00
        lastName: lastName
        relatedUserId: relatedUserId
        countryId: countryId
        redditUrl: https://openapi-generator.tech
        facebookUrl: https://openapi-generator.tech
        websiteUrl: https://openapi-generator.tech
        street: street
        territoryId: territoryId
        socialProfileId: socialProfileId
        email: email
        timestamp: 2000-01-23T04:56:07.000+00:00
        partnerProfileId: partnerProfileId
        stateId: stateId
        languageId: languageId
        primaryContactId: primaryContactId
        identityProviderAccessToken: identityProviderAccessToken
        githubUsername: githubUsername
        tenantId: tenantId
        timezoneId: timezoneId
        faxNumber: faxNumber
        instagramUrl: https://openapi-generator.tech
      properties:
        id:
          nullable: true
          type: string
        timestamp:
          format: date-time
          nullable: true
          type: string
        qualifiedName:
          nullable: true
          readOnly: true
          type: string
        tenantId:
          nullable: true
          type: string
        type:
          enum:
          - Individual
          - Organization
          type: string
        email:
          format: email
          nullable: true
          type: string
        phone:
          format: tel
          nullable: true
          type: string
        publicName:
          nullable: true
          type: string
        firstName:
          nullable: true
          type: string
        lastName:
          nullable: true
          type: string
        jobTitle:
          nullable: true
          type: string
        coverUrl:
          nullable: true
          type: string
        avatarUrl:
          nullable: true
          type: string
        countryId:
          nullable: true
          type: string
        timezoneId:
          nullable: true
          type: string
        languageId:
          nullable: true
          type: string
        socialProfileId:
          nullable: true
          type: string
        webUrl:
          format: uri
          nullable: true
          type: string
        gitHubUrl:
          format: uri
          nullable: true
          type: string
        twitchUrl:
          format: uri
          nullable: true
          type: string
        redditUrl:
          format: uri
          nullable: true
          type: string
        tikTokUrl:
          format: uri
          nullable: true
          type: string
        websiteUrl:
          format: uri
          nullable: true
          type: string
        twitterUrl:
          format: uri
          nullable: true
          type: string
        facebookUrl:
          format: uri
          nullable: true
          type: string
        youTubeUrl:
          format: uri
          nullable: true
          type: string
        linkedInUrl:
          format: uri
          nullable: true
          type: string
        instagramUrl:
          format: uri
          nullable: true
          type: string
        githubUsername:
          nullable: true
          type: string
        duns:
          nullable: true
          type: string
        taxId:
          nullable: true
          type: string
        about:
          nullable: true
          type: string
        street:
          nullable: true
          type: string
        cartId:
          nullable: true
          type: string
        cityId:
          nullable: true
          type: string
        zipCode:
          nullable: true
          type: string
        stateId:
          nullable: true
          type: string
        walletId:
          nullable: true
          type: string
        faxNumber:
          nullable: true
          type: string
        postalCode:
          nullable: true
          type: string
        currencyId:
          nullable: true
          type: string
        streetLine1:
          nullable: true
          type: string
        streetLine2:
          nullable: true
          type: string
        territoryId:
          nullable: true
          type: string
        mobilePhone:
          nullable: true
          type: string
        enrollmentId:
          nullable: true
          type: string
        annualRevenue:
          nullable: true
          type: string
        relatedUserId:
          nullable: true
          type: string
        businessPhone:
          nullable: true
          type: string
        ownerContactId:
          nullable: true
          type: string
        relatedTenantId:
          nullable: true
          type: string
        activityFeedId:
          nullable: true
          type: string
        parentContactId:
          nullable: true
          type: string
        identityProvider:
          nullable: true
          type: string
        partnerProfileId:
          nullable: true
          type: string
        primaryContactId:
          nullable: true
          type: string
        activeDirectoryId:
          nullable: true
          type: string
        identityProviderAccessToken:
          nullable: true
          type: string
        birthday:
          format: date-time
          nullable: true
          type: string
      type: object
    ContactDtoListEnvelope:
      additionalProperties: false
      example:
        result:
        - streetLine2: streetLine2
          zipCode: zipCode
          streetLine1: streetLine1
          jobTitle: jobTitle
          twitterUrl: https://openapi-generator.tech
          postalCode: postalCode
          tikTokUrl: https://openapi-generator.tech
          about: about
          cityId: cityId
          type: Individual
          identityProvider: identityProvider
          publicName: publicName
          id: id
          currencyId: currencyId
          gitHubUrl: https://openapi-generator.tech
          walletId: walletId
          enrollmentId: enrollmentId
          parentContactId: parentContactId
          activeDirectoryId: activeDirectoryId
          linkedInUrl: https://openapi-generator.tech
          avatarUrl: avatarUrl
          qualifiedName: qualifiedName
          cartId: cartId
          relatedTenantId: relatedTenantId
          twitchUrl: https://openapi-generator.tech
          ownerContactId: ownerContactId
          coverUrl: coverUrl
          firstName: firstName
          activityFeedId: activityFeedId
          mobilePhone: mobilePhone
          phone: phone
          webUrl: https://openapi-generator.tech
          taxId: taxId
          duns: duns
          businessPhone: businessPhone
          youTubeUrl: https://openapi-generator.tech
          annualRevenue: annualRevenue
          birthday: 2000-01-23T04:56:07.000+00:00
          lastName: lastName
          relatedUserId: relatedUserId
          countryId: countryId
          redditUrl: https://openapi-generator.tech
          facebookUrl: https://openapi-generator.tech
          websiteUrl: https://openapi-generator.tech
          street: street
          territoryId: territoryId
          socialProfileId: socialProfileId
          email: email
          timestamp: 2000-01-23T04:56:07.000+00:00
          partnerProfileId: partnerProfileId
          stateId: stateId
          languageId: languageId
          primaryContactId: primaryContactId
          identityProviderAccessToken: identityProviderAccessToken
          githubUsername: githubUsername
          tenantId: tenantId
          timezoneId: timezoneId
          faxNumber: faxNumber
          instagramUrl: https://openapi-generator.tech
        - streetLine2: streetLine2
          zipCode: zipCode
          streetLine1: streetLine1
          jobTitle: jobTitle
          twitterUrl: https://openapi-generator.tech
          postalCode: postalCode
          tikTokUrl: https://openapi-generator.tech
          about: about
          cityId: cityId
          type: Individual
          identityProvider: identityProvider
          publicName: publicName
          id: id
          currencyId: currencyId
          gitHubUrl: https://openapi-generator.tech
          walletId: walletId
          enrollmentId: enrollmentId
          parentContactId: parentContactId
          activeDirectoryId: activeDirectoryId
          linkedInUrl: https://openapi-generator.tech
          avatarUrl: avatarUrl
          qualifiedName: qualifiedName
          cartId: cartId
          relatedTenantId: relatedTenantId
          twitchUrl: https://openapi-generator.tech
          ownerContactId: ownerContactId
          coverUrl: coverUrl
          firstName: firstName
          activityFeedId: activityFeedId
          mobilePhone: mobilePhone
          phone: phone
          webUrl: https://openapi-generator.tech
          taxId: taxId
          duns: duns
          businessPhone: businessPhone
          youTubeUrl: https://openapi-generator.tech
          annualRevenue: annualRevenue
          birthday: 2000-01-23T04:56:07.000+00:00
          lastName: lastName
          relatedUserId: relatedUserId
          countryId: countryId
          redditUrl: https://openapi-generator.tech
          facebookUrl: https://openapi-generator.tech
          websiteUrl: https://openapi-generator.tech
          street: street
          territoryId: territoryId
          socialProfileId: socialProfileId
          email: email
          timestamp: 2000-01-23T04:56:07.000+00:00
          partnerProfileId: partnerProfileId
          stateId: stateId
          languageId: languageId
          primaryContactId: primaryContactId
          identityProviderAccessToken: identityProviderAccessToken
          githubUsername: githubUsername
          tenantId: tenantId
          timezoneId: timezoneId
          faxNumber: faxNumber
          instagramUrl: https://openapi-generator.tech
        activityId: activityId
        errorMessage: errorMessage
        correlationId: correlationId
        isSuccess: true
        timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        isSuccess:
          readOnly: true
          type: boolean
        errorMessage:
          nullable: true
          type: string
        correlationId:
          nullable: true
          type: string
        timestamp:
          format: date-time
          readOnly: true
          type: string
        activityId:
          nullable: true
          readOnly: true
          type: string
        result:
          items:
            $ref: '#/components/schemas/ContactDto'
          nullable: true
          type: array
      type: object
    ErrorEnvelope:
      additionalProperties: false
      example:
        activityId: activityId
        errorMessage: errorMessage
        correlationId: correlationId
        isSuccess: true
        timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        isSuccess:
          readOnly: true
          type: boolean
        errorMessage:
          nullable: true
          type: string
        correlationId:
          nullable: true
          type: string
        timestamp:
          format: date-time
          readOnly: true
          type: string
        activityId:
          nullable: true
          readOnly: true
          type: string
      type: object
    ForgotPasswordRequest:
      additionalProperties: false
      example:
        email: email
      properties:
        email:
          nullable: true
          type: string
      required:
      - email
      type: object
    HttpValidationProblemDetails:
      additionalProperties: {}
      properties:
        type:
          nullable: true
          type: string
        title:
          nullable: true
          type: string
        status:
          format: int32
          nullable: true
          type: integer
        detail:
          nullable: true
          type: string
        instance:
          nullable: true
          type: string
        errors:
          additionalProperties:
            items:
              type: string
            type: array
          nullable: true
          type: object
      type: object
    InfoRequest:
      additionalProperties: false
      example:
        oldPassword: oldPassword
        newPassword: newPassword
        newEmail: newEmail
      properties:
        newEmail:
          nullable: true
          type: string
        newPassword:
          nullable: true
          type: string
        oldPassword:
          nullable: true
          type: string
      type: object
    InfoResponse:
      additionalProperties: false
      example:
        email: email
        isEmailConfirmed: true
      properties:
        email:
          nullable: true
          type: string
        isEmailConfirmed:
          type: boolean
      required:
      - email
      - isEmailConfirmed
      type: object
    LoginRequest:
      additionalProperties: false
      example:
        password: password
        twoFactorRecoveryCode: twoFactorRecoveryCode
        email: email
        twoFactorCode: twoFactorCode
      properties:
        email:
          nullable: true
          type: string
        password:
          nullable: true
          type: string
        twoFactorCode:
          nullable: true
          type: string
        twoFactorRecoveryCode:
          nullable: true
          type: string
      required:
      - email
      - password
      type: object
    RefreshRequest:
      additionalProperties: false
      example:
        refreshToken: refreshToken
      properties:
        refreshToken:
          nullable: true
          type: string
      required:
      - refreshToken
      type: object
    RegisterRequest:
      additionalProperties: false
      example:
        password: password
        email: email
      properties:
        email:
          nullable: true
          type: string
        password:
          nullable: true
          type: string
      required:
      - email
      - password
      type: object
    ResendConfirmationEmailRequest:
      additionalProperties: false
      example:
        email: email
      properties:
        email:
          nullable: true
          type: string
      required:
      - email
      type: object
    ResetPasswordRequest:
      additionalProperties: false
      example:
        resetCode: resetCode
        newPassword: newPassword
        email: email
      properties:
        email:
          nullable: true
          type: string
        resetCode:
          nullable: true
          type: string
        newPassword:
          nullable: true
          type: string
      required:
      - email
      - newPassword
      - resetCode
      type: object
    TwoFactorRequest:
      additionalProperties: false
      example:
        resetRecoveryCodes: true
        enable: true
        resetSharedKey: true
        forgetMachine: true
        twoFactorCode: twoFactorCode
      properties:
        enable:
          nullable: true
          type: boolean
        twoFactorCode:
          nullable: true
          type: string
        resetSharedKey:
          type: boolean
        resetRecoveryCodes:
          type: boolean
        forgetMachine:
          type: boolean
      type: object
    TwoFactorResponse:
      additionalProperties: false
      example:
        sharedKey: sharedKey
        isTwoFactorEnabled: true
        isMachineRemembered: true
        recoveryCodesLeft: 0
        recoveryCodes:
        - recoveryCodes
        - recoveryCodes
      properties:
        sharedKey:
          nullable: true
          type: string
        recoveryCodesLeft:
          format: int32
          type: integer
        recoveryCodes:
          items:
            type: string
          nullable: true
          type: array
        isTwoFactorEnabled:
          type: boolean
        isMachineRemembered:
          type: boolean
      required:
      - isMachineRemembered
      - isTwoFactorEnabled
      - recoveryCodesLeft
      - sharedKey
      type: object
    _Account_PerformExternalLogin_post_request:
      properties:
        provider:
          type: string
        returnUrl:
          type: string
      type: object
    _Account_Logout_post_request:
      properties:
        returnUrl:
          type: string
      type: object
    _Account_Manage_LinkExternalLogin_post_request:
      properties:
        provider:
          type: string
      type: object

