openapi: 3.0.4
info:
  contact:
    email: support@fenix-alliance.com
    name: Fenix Alliance Inc.
    url: https://fenixalliance.com.co/Support
  license:
    name: Fenix Alliance Inc.
    url: https://fenix-alliance.com.co/Legal/Policies/eula
  termsOfService: https://absuite.net/eula
  title: ForexService
  version: 2.0.0.0
servers:
- description: Alliance Business Suite API
  url: "{server}"
  variables:
    server:
      default: https://absuite.net
      description: ABS instance base URL
      enum:
      - https://absuite.net
      - https://test.absuite.net
      - https://dev.absuite.net
      - https://localhost:44388
tags:
- name: Exchange
- name: ExchangeV
- name: FenixAlliance.ABP.Web
- name: Rates
paths:
  /api/v2/ForexService/Exchange/Latest:
    get:
      description: Exchange an amount of money from one currency to another using
        the latest available exchange rates.
      operationId: ExchangeAmountAsync
      parameters:
      - explode: true
        in: query
        name: amount
        required: true
        schema:
          format: double
          type: number
        style: form
      - explode: true
        in: query
        name: sourceCurrencyId
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: targetCurrencyId
        required: true
        schema:
          type: string
        style: form
      responses:
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
          description: Forbidden
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
          description: Unauthorized
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MoneyEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/MoneyEnvelope'
          description: OK
      summary: Exchange currency at latest rates
      tags:
      - Exchange
      x-accepts:
      - application/json
      - application/xml
  /api/v2/ForexService/Exchange/History:
    get:
      description: Exchange an amount of money from one currency to another using
        exchange rates from a specific historical date.
      operationId: ExchangeAmountHistoricalAsync
      parameters:
      - explode: true
        in: query
        name: amount
        required: true
        schema:
          format: double
          type: number
        style: form
      - explode: true
        in: query
        name: sourceCurrencyId
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: targetCurrencyId
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: date
        required: true
        schema:
          format: date
          type: string
        style: form
      responses:
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
          description: Forbidden
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
          description: Unauthorized
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MoneyEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/MoneyEnvelope'
          description: OK
      summary: Exchange currency at historical rates
      tags:
      - Exchange
      x-accepts:
      - application/json
      - application/xml
  /api/v3/ForexService/Exchange/Latest:
    get:
      description: Exchange an amount of money from one currency to another using
        the latest available exchange rates. Returns the full ExchangeRate details.
      operationId: ExchangeAmountV3Async
      parameters:
      - explode: true
        in: query
        name: amount
        required: true
        schema:
          format: double
          type: number
        style: form
      - explode: true
        in: query
        name: sourceCurrencyId
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: targetCurrencyId
        required: true
        schema:
          type: string
        style: form
      responses:
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
          description: Forbidden
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
          description: Unauthorized
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExchangeRateEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ExchangeRateEnvelope'
          description: OK
      summary: Exchange currency at latest rates (v3)
      tags:
      - ExchangeV
      x-accepts:
      - application/json
      - application/xml
  /api/v3/ForexService/Exchange/History:
    get:
      description: Exchange an amount of money from one currency to another using
        exchange rates from a specific historical date. Returns the full ExchangeRate
        details.
      operationId: ExchangeAmountHistoricalV3Async
      parameters:
      - explode: true
        in: query
        name: amount
        required: true
        schema:
          format: double
          type: number
        style: form
      - explode: true
        in: query
        name: sourceCurrencyId
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: targetCurrencyId
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: date
        required: true
        schema:
          format: date
          type: string
        style: form
      responses:
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
          description: Forbidden
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
          description: Unauthorized
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExchangeRateEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ExchangeRateEnvelope'
          description: OK
      summary: Exchange currency at historical rates (v3)
      tags:
      - ExchangeV
      x-accepts:
      - application/json
      - application/xml
  /version:
    get:
      responses:
        "200":
          description: OK
      tags:
      - FenixAlliance.ABP.Web
      x-accepts:
      - application/json
  /health:
    get:
      responses:
        "200":
          description: OK
      tags:
      - FenixAlliance.ABP.Web
      x-accepts:
      - application/json
  /hello:
    get:
      responses:
        "200":
          description: OK
      tags:
      - FenixAlliance.ABP.Web
      x-accepts:
      - application/json
  /register:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
        required: true
      responses:
        "200":
          description: OK
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
          description: Bad Request
      tags:
      - FenixAlliance.ABP.Web
      x-content-type: application/json
      x-accepts:
      - application/problem+json
  /login:
    post:
      parameters:
      - explode: true
        in: query
        name: useCookies
        required: false
        schema:
          type: boolean
        style: form
      - explode: true
        in: query
        name: useSessionCookies
        required: false
        schema:
          type: boolean
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessTokenResponse'
          description: OK
      tags:
      - FenixAlliance.ABP.Web
      x-content-type: application/json
      x-accepts:
      - application/json
  /refresh:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessTokenResponse'
          description: OK
      tags:
      - FenixAlliance.ABP.Web
      x-content-type: application/json
      x-accepts:
      - application/json
  /confirmEmail:
    get:
      operationId: MapIdentityApi-/confirmEmail
      parameters:
      - explode: true
        in: query
        name: userId
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: code
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: changedEmail
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          description: OK
      tags:
      - FenixAlliance.ABP.Web
      x-accepts:
      - application/json
  /resendConfirmationEmail:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResendConfirmationEmailRequest'
        required: true
      responses:
        "200":
          description: OK
      tags:
      - FenixAlliance.ABP.Web
      x-content-type: application/json
      x-accepts:
      - application/json
  /forgotPassword:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ForgotPasswordRequest'
        required: true
      responses:
        "200":
          description: OK
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
          description: Bad Request
      tags:
      - FenixAlliance.ABP.Web
      x-content-type: application/json
      x-accepts:
      - application/problem+json
  /resetPassword:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPasswordRequest'
        required: true
      responses:
        "200":
          description: OK
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
          description: Bad Request
      tags:
      - FenixAlliance.ABP.Web
      x-content-type: application/json
      x-accepts:
      - application/problem+json
  /manage/2fa:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TwoFactorRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TwoFactorResponse'
          description: OK
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
          description: Bad Request
        "404":
          description: Not Found
      tags:
      - FenixAlliance.ABP.Web
      x-content-type: application/json
      x-accepts:
      - application/json
      - application/problem+json
  /manage/info:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InfoResponse'
          description: OK
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
          description: Bad Request
        "404":
          description: Not Found
      tags:
      - FenixAlliance.ABP.Web
      x-accepts:
      - application/json
      - application/problem+json
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InfoRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InfoResponse'
          description: OK
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
          description: Bad Request
        "404":
          description: Not Found
      tags:
      - FenixAlliance.ABP.Web
      x-content-type: application/json
      x-accepts:
      - application/json
      - application/problem+json
  /api/v2/ForexService/Rates/Latest:
    get:
      description: Retrieves the latest exchange rates for all supported currencies.
      operationId: GetLatestCurrencyRatesModelAsync
      parameters:
      - explode: true
        in: query
        name: api-version
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: header
        name: x-api-version
        required: false
        schema:
          type: string
        style: simple
      responses:
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
          description: Forbidden
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
          description: Unauthorized
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForexRatesDtoEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ForexRatesDtoEnvelope'
          description: OK
      summary: Get latest currency rates
      tags:
      - Rates
      x-accepts:
      - application/json
      - application/xml
  /api/v2/ForexService/Rates/Latest/{currencyId}:
    get:
      description: Retrieves the latest exchange rate for a specific currency by its
        identifier.
      operationId: GetLatestCurrencyRateAsync
      parameters:
      - explode: false
        in: path
        name: currencyId
        required: true
        schema:
          type: string
        style: simple
      - explode: true
        in: query
        name: api-version
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: header
        name: x-api-version
        required: false
        schema:
          type: string
        style: simple
      responses:
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
          description: Forbidden
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
          description: Unauthorized
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExchangeRateEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ExchangeRateEnvelope'
          description: OK
      summary: Get latest rate for a currency
      tags:
      - Rates
      x-accepts:
      - application/json
      - application/xml
  /api/v2/ForexService/Rates/History:
    get:
      description: Retrieves exchange rates for all supported currencies as of a specific
        historical date.
      operationId: GetHistoricalCurrencyRatesAsync
      parameters:
      - explode: true
        in: query
        name: date
        required: false
        schema:
          format: date-time
          type: string
        style: form
      - explode: true
        in: query
        name: api-version
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: header
        name: x-api-version
        required: false
        schema:
          type: string
        style: simple
      responses:
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
          description: Forbidden
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
          description: Unauthorized
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForexRatesDtoEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ForexRatesDtoEnvelope'
          description: OK
      summary: Get historical currency rates
      tags:
      - Rates
      x-accepts:
      - application/json
      - application/xml
  /api/v2/ForexService/Rates/History/{currencyId}:
    get:
      description: Retrieves the exchange rate for a specific currency as of a specific
        historical date.
      operationId: GetHistoricalCurrencyRateAsync
      parameters:
      - explode: false
        in: path
        name: currencyId
        required: true
        schema:
          type: string
        style: simple
      - explode: true
        in: query
        name: date
        required: false
        schema:
          format: date-time
          type: string
        style: form
      - explode: true
        in: query
        name: api-version
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: header
        name: x-api-version
        required: false
        schema:
          type: string
        style: simple
      responses:
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
          description: Forbidden
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorEnvelope'
          description: Unauthorized
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExchangeRateEnvelope'
            application/xml:
              schema:
                $ref: '#/components/schemas/ExchangeRateEnvelope'
          description: OK
      summary: Get historical rate for a currency
      tags:
      - Rates
      x-accepts:
      - application/json
      - application/xml
components:
  schemas:
    AccessTokenResponse:
      additionalProperties: false
      example:
        expiresIn: 0
        tokenType: tokenType
        accessToken: accessToken
        refreshToken: refreshToken
      properties:
        tokenType:
          nullable: true
          readOnly: true
          type: string
        accessToken:
          nullable: true
          type: string
        expiresIn:
          format: int64
          type: integer
        refreshToken:
          nullable: true
          type: string
      required:
      - accessToken
      - expiresIn
      - refreshToken
      type: object
    CurrencyId:
      additionalProperties: false
      example:
        country: country
        code: code
        value: value
      properties:
        value:
          nullable: true
          readOnly: true
          type: string
        code:
          nullable: true
          type: string
        country:
          nullable: true
          type: string
      type: object
    ErrorEnvelope:
      additionalProperties: false
      example:
        activityId: activityId
        errorMessage: errorMessage
        correlationId: correlationId
        isSuccess: true
        timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        isSuccess:
          readOnly: true
          type: boolean
        errorMessage:
          nullable: true
          type: string
        correlationId:
          nullable: true
          type: string
        timestamp:
          format: date-time
          readOnly: true
          type: string
        activityId:
          nullable: true
          readOnly: true
          type: string
      type: object
    ExchangeRate:
      additionalProperties: false
      example:
        rate:
          amount: 0.8008281904610115
          currency:
            country: country
            code: code
            value: value
        source:
          amount: 0.8008281904610115
          currency:
            country: country
            code: code
            value: value
        target:
          amount: 0.8008281904610115
          currency:
            country: country
            code: code
            value: value
      properties:
        source:
          $ref: '#/components/schemas/Money'
        target:
          $ref: '#/components/schemas/Money'
        rate:
          $ref: '#/components/schemas/Money'
      type: object
    ExchangeRateEnvelope:
      additionalProperties: false
      example:
        result:
          rate:
            amount: 0.8008281904610115
            currency:
              country: country
              code: code
              value: value
          source:
            amount: 0.8008281904610115
            currency:
              country: country
              code: code
              value: value
          target:
            amount: 0.8008281904610115
            currency:
              country: country
              code: code
              value: value
        activityId: activityId
        errorMessage: errorMessage
        correlationId: correlationId
        isSuccess: true
        timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        isSuccess:
          readOnly: true
          type: boolean
        errorMessage:
          nullable: true
          type: string
        correlationId:
          nullable: true
          type: string
        timestamp:
          format: date-time
          readOnly: true
          type: string
        activityId:
          nullable: true
          readOnly: true
          type: string
        result:
          $ref: '#/components/schemas/ExchangeRate'
      type: object
    ForexRatesDto:
      additionalProperties: false
      example:
        date: date
        requestTimestamp: 2000-01-23T04:56:07.000+00:00
        success: true
        rates:
          key: 6.027456183070403
        base: base
        timestamp: 0
      properties:
        success:
          type: boolean
        date:
          nullable: true
          type: string
        base:
          nullable: true
          type: string
        timestamp:
          format: int64
          type: integer
        requestTimestamp:
          format: date-time
          type: string
        rates:
          additionalProperties:
            format: double
            type: number
          nullable: true
          type: object
      type: object
    ForexRatesDtoEnvelope:
      additionalProperties: false
      example:
        result:
          date: date
          requestTimestamp: 2000-01-23T04:56:07.000+00:00
          success: true
          rates:
            key: 6.027456183070403
          base: base
          timestamp: 0
        activityId: activityId
        errorMessage: errorMessage
        correlationId: correlationId
        isSuccess: true
        timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        isSuccess:
          readOnly: true
          type: boolean
        errorMessage:
          nullable: true
          type: string
        correlationId:
          nullable: true
          type: string
        timestamp:
          format: date-time
          readOnly: true
          type: string
        activityId:
          nullable: true
          readOnly: true
          type: string
        result:
          $ref: '#/components/schemas/ForexRatesDto'
      type: object
    ForgotPasswordRequest:
      additionalProperties: false
      example:
        email: email
      properties:
        email:
          nullable: true
          type: string
      required:
      - email
      type: object
    HttpValidationProblemDetails:
      additionalProperties: {}
      properties:
        type:
          nullable: true
          type: string
        title:
          nullable: true
          type: string
        status:
          format: int32
          nullable: true
          type: integer
        detail:
          nullable: true
          type: string
        instance:
          nullable: true
          type: string
        errors:
          additionalProperties:
            items:
              type: string
            type: array
          nullable: true
          type: object
      type: object
    InfoRequest:
      additionalProperties: false
      example:
        oldPassword: oldPassword
        newPassword: newPassword
        newEmail: newEmail
      properties:
        newEmail:
          nullable: true
          type: string
        newPassword:
          nullable: true
          type: string
        oldPassword:
          nullable: true
          type: string
      type: object
    InfoResponse:
      additionalProperties: false
      example:
        email: email
        isEmailConfirmed: true
      properties:
        email:
          nullable: true
          type: string
        isEmailConfirmed:
          type: boolean
      required:
      - email
      - isEmailConfirmed
      type: object
    LoginRequest:
      additionalProperties: false
      example:
        password: password
        twoFactorRecoveryCode: twoFactorRecoveryCode
        email: email
        twoFactorCode: twoFactorCode
      properties:
        email:
          nullable: true
          type: string
        password:
          nullable: true
          type: string
        twoFactorCode:
          nullable: true
          type: string
        twoFactorRecoveryCode:
          nullable: true
          type: string
      required:
      - email
      - password
      type: object
    Money:
      additionalProperties: false
      example:
        amount: 0.8008281904610115
        currency:
          country: country
          code: code
          value: value
      properties:
        amount:
          format: double
          type: number
        currency:
          $ref: '#/components/schemas/CurrencyId'
      type: object
    MoneyEnvelope:
      additionalProperties: false
      example:
        result:
          amount: 0.8008281904610115
          currency:
            country: country
            code: code
            value: value
        activityId: activityId
        errorMessage: errorMessage
        correlationId: correlationId
        isSuccess: true
        timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        isSuccess:
          readOnly: true
          type: boolean
        errorMessage:
          nullable: true
          type: string
        correlationId:
          nullable: true
          type: string
        timestamp:
          format: date-time
          readOnly: true
          type: string
        activityId:
          nullable: true
          readOnly: true
          type: string
        result:
          $ref: '#/components/schemas/Money'
      type: object
    RefreshRequest:
      additionalProperties: false
      example:
        refreshToken: refreshToken
      properties:
        refreshToken:
          nullable: true
          type: string
      required:
      - refreshToken
      type: object
    RegisterRequest:
      additionalProperties: false
      example:
        password: password
        email: email
      properties:
        email:
          nullable: true
          type: string
        password:
          nullable: true
          type: string
      required:
      - email
      - password
      type: object
    ResendConfirmationEmailRequest:
      additionalProperties: false
      example:
        email: email
      properties:
        email:
          nullable: true
          type: string
      required:
      - email
      type: object
    ResetPasswordRequest:
      additionalProperties: false
      example:
        resetCode: resetCode
        newPassword: newPassword
        email: email
      properties:
        email:
          nullable: true
          type: string
        resetCode:
          nullable: true
          type: string
        newPassword:
          nullable: true
          type: string
      required:
      - email
      - newPassword
      - resetCode
      type: object
    TwoFactorRequest:
      additionalProperties: false
      example:
        resetRecoveryCodes: true
        enable: true
        resetSharedKey: true
        forgetMachine: true
        twoFactorCode: twoFactorCode
      properties:
        enable:
          nullable: true
          type: boolean
        twoFactorCode:
          nullable: true
          type: string
        resetSharedKey:
          type: boolean
        resetRecoveryCodes:
          type: boolean
        forgetMachine:
          type: boolean
      type: object
    TwoFactorResponse:
      additionalProperties: false
      example:
        sharedKey: sharedKey
        isTwoFactorEnabled: true
        isMachineRemembered: true
        recoveryCodesLeft: 0
        recoveryCodes:
        - recoveryCodes
        - recoveryCodes
      properties:
        sharedKey:
          nullable: true
          type: string
        recoveryCodesLeft:
          format: int32
          type: integer
        recoveryCodes:
          items:
            type: string
          nullable: true
          type: array
        isTwoFactorEnabled:
          type: boolean
        isMachineRemembered:
          type: boolean
      required:
      - isMachineRemembered
      - isTwoFactorEnabled
      - recoveryCodesLeft
      - sharedKey
      type: object

